### PR TITLE
[#82] Adds proxy as a flag and config option

### LINKED ISSUE #82: does not work behind a proxy (windows)
I tried tool-sync on 2 machines. On the machine which uses a proxy the `tool sync` command does not work...

Is there a way to config tool-sync for using a proxy?

### PR DESCRIPTION
**Pull request by MitchellBerend**
Resolves #82 

This pr adds a proxy flag and a proxy option to the `tool.toml`, if both are supplied the proxy flag supersedes the config option.

### Additional tasks

- [ ] Documentation for changes provided/changed
- [ ] Tests added
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by MitchellBerend** [comment]
@chshersh @maku can you both check this out? This implementation functionally works for me, but I don't see a way to actually test this.

File: src/config/schema.rs [hunk 1]
```diff
@@ -38,6 +39,9 @@ pub struct ConfigAsset {
 
     /// Name of the specific asset to download
     pub asset_name: AssetName,
+
+    /// Proxy which will get used for all communication
+    pub proxy: Option<ureq::Proxy>,
```
Comment (chshersh) [inline src/config/schema.rs:44]: Is there a particular reason we may need a different proxy for individual assets?

File: src/config/toml.rs [hunk 2]
```diff
@@ -40,54 +44,73 @@ pub fn with_parsed_file<F: FnOnce(Config)>(config_path: PathBuf, on_success: F)
...
-fn decode_config(toml: Value) -> Option<Config> {
+fn decode_config(toml: Value, proxy: Option<String>) -> Option<Config> {
     let str_store_directory = toml.get("store_directory")?.as_str()?;
+    let proxy = match proxy {
+        Some(p) => Some(p),
+        None => match toml.get("proxy") {
+            Some(p) => Some(p.as_str()?.into()),
+            None => None,
+        },
+    };
```
Comment (chshersh) [inline src/config/toml.rs:71]: Looks like we can implement it easier using `.or_else()`

File: src/sync/install.rs [hunk 3]
```diff
@@ -82,7 +82,10 @@ impl<'a> Installer<'a> {
         match archive {
             None => Err(format!("Unsupported asset type: {}", tool_asset.asset.name).into()),
             Some(archive) => match archive.unpack() {
-                Err(unpack_err) => Err(unpack_err.to_string().into()),
+                Err(unpack_err) => {
+                    println!("{:?}", &tool_asset);
```
Comment (chshersh) [inline src/sync/install.rs:86]: Leftover debug print?

**Review by chshersh — COMMENTED** [review]
I don't use a proxy so I can't verify whether this works or not 😞 

If anyone who uses `proxy` can test if this really does the job, it would be much appreciated!

cc @maku

File: src/config/schema.rs (hunk 1 above)
Comment (MitchellBerend) [reply src/config/schema.rs:44]: https://github.com/chshersh/tool-sync/blob/2b752bc1ec88672fde210bffef66f86800b7f601/src/sync/prefetch.rs#L76-L101

This method makes the first call to the github api. It only has access to the names and `ConfigAsset` struct.

The implementation of this was kind of messy so there could be a better way to implement this so the `Client` gets recycled for each api call instead of a new instance being created for every tool.

**Comment by chshersh** [comment]
Thanks for working on this, @MitchellBerend! 👏🏻 

Just a heads-up, I have more suggestions about changing the code. But before putting more work into this, I'd like to have a confirmation that the feature works. I don't use any proxy and once this feature is merged, it will probably remain in the code forever and require maintenance.

Spending more of my free time maintaining features I don't even use is not something I'm eager to do 😌 
And it's even worse if nobody else is going to use them either 😢

**Comment by maku** [comment]
@MitchellBerend @chshersh sorry for delay, recently I worked mostly remote where I do not have a proxy server. But today I tried the implementation (I cloned https://github.com/MitchellBerend/tool-sync).

**Comment by chshersh** [comment]
@maku Thanks for checking the implementation!

In that case, I'm happy to accept the patch 🙂 I'll get around providing more feedback on the implementation once I have time 👌🏻

**Comment by MitchellBerend** [comment]
@maku what os are you on? I would also like to know if this works on windows.

Should auth not be supported on this? My use case also does not require auth so I did not implement it. Support for this can always be added later when needed so maybe this is work that doesn't need to be done right now.

**Comment by maku** [comment]
@MitchellBerend I tried it on windows

**Review by chshersh — APPROVED** [review]
Okay, I'm happy to merge it because it works 👍🏻 

I'll create a separate issue to improve the implementation

**Comment by chshersh** [comment]
And here is the issue with the future improvements suggestions:

* https://github.com/chshersh/tool-sync/issues/130
