### PR TITLE
Provide more detailed TOML decoding errors

### LINKED ISSUE #25: Provide more detailed TOML decoding errors
Currently, when TOML decoding fails due to missing fields or mismatched values, the error doesn't specify the missing field:

```
Error parsing configuration at path Cargo.toml: [Decode Error]
```

The corresponding function also simply returns `Option<Config>` instead of providing more details

https://github.com/chshersh/tool-sync/blob/950b4028a619d33303548acd06056949dcec1a4a/src/config/toml.rs#L48-L64

It would provide better UX to add more details to the `DecodeError` constructor in the `TomlError` type by telling all errors that happened during decoding:

https://github.com/chshersh/tool-sync/blob/950b4028a619d33303548acd06056949dcec1a4a/src/config/toml.rs#L10-L14

Open questions:

* Does the `toml` crate provide better decoding than `as_str()` and friends? All such functions return `Option<...>` while it would be better to have `Result<..., ...>`
* Does Rust have the analogue of the Haskell's `Validation` type to combine multiple errors and which can be used with `toml`?

### PR DESCRIPTION
**Pull request by DukeManh**
Fixes #25 

Provide more detailed TOML decoding errors by adding `DecodeError` enum to represent different error types.

Author's questions:

> Does the toml crate provide better decoding than as_str() and friends? All such functions return Option<...> while it would be better to have Result<..., ...>

I couldn't find better decoding than as_str() but I did map `Option<>` to `Result<_, DecodeError>` so I guess dealing with Option is fine?

### Additional tasks

- [ ] Documentation for changes provided/changed
- [x] Tests added
- [ ] Updated CHANGELOG.md

### CODE REVIEW

File: src/config/toml.rs [hunk 1]
```diff
@@ -12,15 +12,32 @@ use crate::model::asset_name::AssetName;
...
     IO(String),
     Parse(toml::de::Error),
-    Decode,
+    Decode(DecodeError),
+}
+
+#[derive(Debug, PartialEq, Eq)]
+pub enum DecodeError {
+    NoStoreDirectory,
+    NotATable,
```
Comment (DukeManh) [inline src/config/toml.rs:21]: I'm not sure how to trigger this error case yet though it can happen on line 85. I find out that the config file is always a table if we have `store_directory` defined, which is checked before line 85.

**Review by chshersh — CHANGES_REQUESTED** [review]
Hey @DukeManh,

That's a great start! I propose to go one step further and implement the following design:

- [ ] Introduce a separate data type for `TOML` value types:

```rust
enum TomlType {
    String,
    Integer,
    Float,
    Boolean,
    Datetime,
    Array,
    Table,
}
```

- [ ] Implement `DecodeError` as the following enum, listing all possible errors (very similar to yours but with a few changes):

```rust
pub enum DecodeError {
    /// Missing required TOML key
    MissingKey { key: String },

    /// Expecting a different type of an existing key
    InvalidType { key: String, expected: TomlType, found: toml::Value },
}
```

- [ ] Then, create a `Result<_, DecodeError>` versions of all standard functions from `toml` (but not like all-all, it's not enough only for those that we use. I believe, it's only `as_str` and `as_table`). So it should look something like this:

```rust
fn parse_str(toml: &toml::Value, key: &str) -> Result<String, DecodeError> { ... }
```

In that case, I believe we should be able to use the `?` operator and return the first found error.

Ideally, we want to return all possible errors at once. But that would be more complicated so let's start with this 😌

**Comment by DukeManh** [comment]
@chshersh That's a great suggestion, I'm on it.

**Comment by DukeManh** [comment]
I have some questions.

> Introduce a separate data type for TOML value types

Why do we need a separate type for toml and not use `toml::value`?
>  we want to return all possible errors at once.

Is it something you have in mind? https://doc.rust-lang.org/rust-by-example/error/multiple_error_types.html

**Comment by chshersh** [comment]
> Why do we need a separate type for toml and not use toml::value?

`toml::Value` also stores data inside. When we decode TOML, we don't expect any specific data, we expect only the shape of Data. So, unfortunately, we can't reuse `toml::Value` here.

> Is it something you have in mind? https://doc.rust-lang.org/rust-by-example/error/multiple_error_types.html

No, more like something similar:

* https://www.fpcomplete.com/blog/collect-rust-traverse-haskell-scala/#validation

**Comment by DukeManh** [comment]
@chshersh this is ready, can you review it, please?

File: src/config/toml.rs [hunk 2]
```diff
@@ -8,23 +8,85 @@ use crate::config::schema::{Config, ConfigAsset};
...
+        key: String,
+    },
+    InvalidType {
+        key: String,
+        expected: TomlType,
+        found: Value,
+    },
+}
+
+#[allow(dead_code)]
```
Comment (chshersh) [inline src/config/toml.rs:30]: Just curious why this line is needed? 🤔

File: src/config/toml.rs [hunk 3]
```diff
@@ -50,25 +112,38 @@ fn parse_string(contents: &str) -> Result<Config, TomlError> {
     contents
         .parse::<Value>()
         .map_err(TomlError::Parse)
-        .and_then(|toml| match decode_config(toml) {
-            None => Err(TomlError::Decode),
-            Some(config) => Ok(config),
-        })
+        .and_then(|toml| decode_config(toml).map_err(TomlError::Decode))
```
Comment (chshersh) [inline src/config/toml.rs:115]: That's a neat simplification enabled by the improvement! 💯

File: src/config/toml.rs [hunk 4]
```diff
@@ -8,23 +8,85 @@ use crate::config::schema::{Config, ConfigAsset};
...
+                key,
+                expected,
+                found,
+            } => write!(
+                f,
+                "unexpected value type '{}={}': expected `{}`, found `{}`",
+                key,
+                found,
+                expected,
+                found.type_str()
```
Comment (chshersh) [inline src/config/toml.rs:68]: Wow, `type_str` is a neat function! I didn't know it exists and it's actually the idea behind the `TomlType` enum.

File: src/config/toml.rs [hunk 5]
```diff
@@ -8,23 +8,85 @@ use crate::config::schema::{Config, ConfigAsset};
...
+impl Display for TomlType {
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        let name = match self {
+            TomlType::String => "string",
+            TomlType::Integer => "integer",
+            TomlType::Float => "float",
+            TomlType::Boolean => "boolean",
+            TomlType::DateTime => "datetime",
+            TomlType::Array => "array",
+            TomlType::Table => "table",
```
Comment (chshersh) [inline src/config/toml.rs:83]: Would be nice to reuse `type_str` here and avoid duplication but I don't see a non-ugly way to do this 🤔

File: src/config/toml.rs [hunk 6]
```diff
@@ -50,25 +112,38 @@ fn parse_string(contents: &str) -> Result<Config, TomlError> {
...
+                found: other.clone(),
+            }),
+        },
+    )?;
 
     let mut tools = BTreeMap::new();
 
-    for (key, val) in toml.as_table()?.iter() {
+    // toml is always a table if 'store_directory' is defined above
+    let table = toml.as_table().unwrap();
```
Comment (chshersh) [inline src/config/toml.rs:138]: Could we use `expect` with a unique message string here instead of `unwrap`?

File: src/config/toml.rs [hunk 7]
```diff
@@ -8,23 +8,85 @@ use crate::config::schema::{Config, ConfigAsset};
...
+            TomlError::Decode(e) => write!(f, "[Decode Error] {}", e),
+        }
+    }
+}
+
+impl Display for DecodeError {
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        match self {
+            DecodeError::MissingKey { key } => {
+                write!(f, "'{}' is not configured", key)
```
Comment (chshersh) [inline src/config/toml.rs:56]: Let's change a wording a bit here
```suggestion
                write!(f, "The key '{}' is missing (a typo or not specified?)", key)
```

**Review by chshersh — CHANGES_REQUESTED** [review]
This looks excellent! 👏🏻 
I expected waaaay more changes to support this but it turned out to be quite small 🙂 

I have a few stylistic suggestions and some questions. But overall, the direction is correct 👍🏻

File: src/config/toml.rs (hunk 2 above)
Comment (DukeManh) [reply src/config/toml.rs:30]: The compiler warns that I'm only using `TomlType::String` on line 129 so other types are unused. I am just doing this to suppress that. Maybe comment out the used types for now?

File: src/config/toml.rs (hunk 6 above)
Comment (DukeManh) [reply src/config/toml.rs:138]: nice, I didn't know it existed

**Comment by DukeManh** [comment]
@chshersh, I decided to reuse `toml::Value` and `type_str` to represent our expected type. What do you think?

**Review by chshersh — APPROVED** [review]
I like this implementation! Indeed, it's much simpler 🙂 
Thanks a lot for improving error messages! 👏🏻
